//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecommunication_System.CustomerPage2
{
    public partial class RemPlanAmount
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// MobileNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox MobileNumber;

        /// <summary>
        /// PlanName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PlanName;

        /// <summary>
        /// ShowRemainingAmount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button ShowRemainingAmountbutton;


        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
